import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import ".././globals.css";
import Discover from "@/components/customComponents/Discover/Discover";
import CategoriesLayoutComponent from "@/components/customComponents/Categories/CategoriesLayout";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Discover Manga",
    description: "Generated by create next app",
};

export default function CategoriesLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className=" pt-4">
            <CategoriesLayoutComponent />
            {children}
        </div>
    );
}
