import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import ".././globals.css";
import {
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
} from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import { myListArrs } from '@/lib/constants'
import DiscoverSlugOverview from "@/components/customComponents/Discover/Slug/DiscoverSlugOverview";
import DiscoverSlugOverviewComponent from "@/components/customComponents/Discover/Slug/DiscoverSlugOverviewComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Discover Manga",
    description: "Generated by create next app",
};

export default function DiscoverSlugLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className='p-3 tw-fc w-full'>
            <Tabs defaultValue="overview" className="max-w-screen-lg w-full mx-auto">
                <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="overview">Overview</TabsTrigger>
                    <TabsTrigger value="chapter">Chapter</TabsTrigger>
                </TabsList>
                <DiscoverSlugOverviewComponent />
                <TabsContent value="chapter">
                    {children}
                </TabsContent>
            </Tabs>
        </div>
    );
}
